// Code generated by github.com/oreqizer/go-relaygen, DO NOT EDIT.

package example

import "github.com/oreqizer/go-relaygen/relay"

/*
AdminEdge is an interface holding a node and a cursor

https://facebook.github.io/relay/graphql/connections.htm#sec-Edge-Types
*/
type AdminEdge struct {
	Node   *Admin `json:"node"`
	Cursor string `json:"cursor"`
}

/*
AdminConnection holds information about a connection

https://facebook.github.io/relay/graphql/connections.htm#sec-Reserved-Types
*/
type AdminConnection struct {
	Edges    []*AdminEdge   `json:"edges"`
	PageInfo relay.PageInfo `json:"pageInfo"`
}

/*
AdminConnectionFromArray creates a connection from an array of nodes
*/
func AdminConnectionFromArray(nodes []*Admin, args *relay.ConnectionArgs) *AdminConnection {
	if args == nil {
		return nil
	}

	edges := make([]*AdminEdge, len(nodes))
	for i, n := range nodes {
		edges[i] = &AdminEdge{
			Node:   n,
			Cursor: n.ID(),
		}
	}

	return adminEdgesToReturn(edges, args.Before, args.After, args.First, args.Last)
}

/*
adminEdgesToReturn slices edges according to arguments, returning a connection

Consider returning an error like in
https://facebook.github.io/relay/graphql/connections.htm#sec-Pagination-algorithm
*/
func adminEdgesToReturn(all []*AdminEdge, before, after *string, first, last *int) *AdminConnection {
	edges := adminApplyCursorsToEdges(all, before, after)

	if first != nil && *first > 0 && *first < len(edges) {
		edges = edges[:*first]
	}

	if last != nil && *last > 0 && *last < len(edges) {
		edges = edges[len(edges)-*last:]
	}

	var startCursor, endCursor *string
	if len(edges) > 0 {
		if fst := edges[0]; fst != nil {
			str := fst.Cursor
			startCursor = &str
		}

		if lst := edges[len(edges)-1]; lst != nil {
			str := lst.Cursor
			endCursor = &str
		}
	}

	return &AdminConnection{
		Edges: edges,
		PageInfo: relay.PageInfo{
			HasPreviousPage: adminHasPreviousPage(all, before, after, last),
			HasNextPage:     adminHasNextPage(all, before, after, first),
			StartCursor:     startCursor,
			EndCursor:       endCursor,
		},
	}
}

/*
adminApplyCursorsToEdges slices edges according to cursors
*/
func adminApplyCursorsToEdges(all []*AdminEdge, before, after *string) []*AdminEdge {
	edges := all
	if after != nil {
		for i, e := range edges {
			if e.Cursor == *after {
				edges = edges[i:]
				break
			}
		}
	}

	if before != nil {
		for i, e := range edges {
			if e.Cursor == *before {
				edges = edges[:i+1]
				break
			}
		}
	}
	return edges
}

/*
adminHasPreviousPage determines whether there's a previous page according to cursors

https://facebook.github.io/relay/graphql/connections.htm#sec-undefined.PageInfo.Fields
*/
func adminHasPreviousPage(all []*AdminEdge, before, after *string, last *int) bool {
	if last != nil && *last > 0 {
		edges := adminApplyCursorsToEdges(all, before, after)
		return len(edges) > *last
	}

	return false
}

/*
adminHasNextPage determines whether there's another page according to cursors

https://facebook.github.io/relay/graphql/connections.htm#sec-undefined.PageInfo.Fields
*/
func adminHasNextPage(all []*AdminEdge, before, after *string, first *int) bool {
	if first != nil && *first > 0 {
		edges := adminApplyCursorsToEdges(all, before, after)
		return len(edges) > *first
	}

	return false
}
