// Code generated by github.com/oreqizer/go-relaygen, DO NOT EDIT.

package example

import "github.com/oreqizer/go-relaygen/relay"

/*
UserEdge is an interface holding a node and a cursor

https://facebook.github.io/relay/graphql/connections.htm#sec-Edge-Types
*/
type UserEdge struct {
	Node   *User  `json:"node"`
	Cursor string `json:"cursor"`
}

/*
UserConnection holds information about a connection

https://facebook.github.io/relay/graphql/connections.htm#sec-Reserved-Types
*/
type UserConnection struct {
	Edges    []*UserEdge    `json:"edges"`
	PageInfo relay.PageInfo `json:"pageInfo"`
}

/*
UserConnectionFromArray creates a connection from an array of nodes
*/
func UserConnectionFromArray(nodes []*User, args *relay.ConnectionArgs) *UserConnection {
	if args == nil {
		return nil
	}

	edges := make([]*UserEdge, len(nodes))
	for i, n := range nodes {
		edges[i] = &UserEdge{
			Node:   n,
			Cursor: n.ID(),
		}
	}

	return userEdgesToReturn(edges, args.Before, args.After, args.First, args.Last)
}

/*
userEdgesToReturn slices edges according to arguments, returning a connection

Consider returning an error like in
https://facebook.github.io/relay/graphql/connections.htm#sec-Pagination-algorithm
*/
func userEdgesToReturn(all []*UserEdge, before, after *string, first, last *int) *UserConnection {
	edges := userApplyCursorsToEdges(all, before, after)

	if first != nil && *first > 0 && *first < len(edges) {
		edges = edges[:*first]
	}

	if last != nil && *last > 0 && *last < len(edges) {
		edges = edges[len(edges)-*last:]
	}

	var startCursor, endCursor *string
	if len(edges) > 0 {
		if fst := edges[0]; fst != nil {
			str := fst.Cursor
			startCursor = &str
		}

		if lst := edges[len(edges)-1]; lst != nil {
			str := lst.Cursor
			endCursor = &str
		}
	}

	return &UserConnection{
		Edges: edges,
		PageInfo: relay.PageInfo{
			HasPreviousPage: userHasPreviousPage(all, before, after, last),
			HasNextPage:     userHasNextPage(all, before, after, first),
			StartCursor:     startCursor,
			EndCursor:       endCursor,
		},
	}
}

/*
userApplyCursorsToEdges slices edges according to cursors
*/
func userApplyCursorsToEdges(all []*UserEdge, before, after *string) []*UserEdge {
	edges := all
	if after != nil {
		for i, e := range edges {
			if e.Cursor == *after {
				edges = edges[i:]
				break
			}
		}
	}

	if before != nil {
		for i, e := range edges {
			if e.Cursor == *before {
				edges = edges[:i+1]
				break
			}
		}
	}
	return edges
}

/*
userHasPreviousPage determines whether there's a previous page according to cursors

https://facebook.github.io/relay/graphql/connections.htm#sec-undefined.PageInfo.Fields
*/
func userHasPreviousPage(all []*UserEdge, before, after *string, last *int) bool {
	if last != nil && *last > 0 {
		edges := userApplyCursorsToEdges(all, before, after)
		return len(edges) > *last
	}

	return false
}

/*
userHasNextPage determines whether there's another page according to cursors

https://facebook.github.io/relay/graphql/connections.htm#sec-undefined.PageInfo.Fields
*/
func userHasNextPage(all []*UserEdge, before, after *string, first *int) bool {
	if first != nil && *first > 0 {
		edges := userApplyCursorsToEdges(all, before, after)
		return len(edges) > *first
	}

	return false
}
