package generator

import (
	"text/template"
)

var test = template.Must(template.New("generated").
	Funcs(template.FuncMap{
		"lcFirst": lcFirst,
	}).
	Parse(`
// Code generated by github.com/oreqizer/go-relaygen, DO NOT EDIT.

package {{ .Package }}

import (
	"github.com/oreqizer/go-relaygen/relay"
	"testing"
)

var (
	ONESTR   = "1"
	TWOSTR   = "2"
	THREESTR = "3"
	FOURSTR  = "4"
	FIVESTR  = "5"
)

var (
	ZERO = 0
	ONE  = 1
	TWO  = 2
	// THREE = 3
	FOUR = 4
	// FIVE  = 5
	SIX = 6
)

var nodes{{ .Name }} = []*{{ .Name }}{
	&{{ .Name }}{},
	&{{ .Name }}{},
	&{{ .Name }}{},
	&{{ .Name }}{},
	&{{ .Name }}{},
}

var edges{{ .Name }} = []*{{ .Name }}Edge{
	{{"{"}}Node: &{{ .Name }}{}, Cursor: ONESTR},
	{{"{"}}Node: &{{ .Name }}{}, Cursor: TWOSTR},
	{{"{"}}Node: &{{ .Name }}{}, Cursor: THREESTR},
	{{"{"}}Node: &{{ .Name }}{}, Cursor: FOURSTR},
	{{"{"}}Node: &{{ .Name }}{}, Cursor: FIVESTR},
}

func init() {
	nodes{{ .Name }}[0].{{ .ID }} = ONESTR
	nodes{{ .Name }}[1].{{ .ID }} = TWOSTR
	nodes{{ .Name }}[2].{{ .ID }} = THREESTR
	nodes{{ .Name }}[3].{{ .ID }} = FOURSTR
	nodes{{ .Name }}[4].{{ .ID }} = FIVESTR

	edges{{ .Name }}[0].Node.{{ .ID }} = ONESTR
	edges{{ .Name }}[1].Node.{{ .ID }} = TWOSTR
	edges{{ .Name }}[2].Node.{{ .ID }} = THREESTR
	edges{{ .Name }}[3].Node.{{ .ID }} = FOURSTR
	edges{{ .Name }}[4].Node.{{ .ID }} = FIVESTR
}

var table{{ .Name }}ConnectionFromArray = []struct {
	nodes []*{{ .Name }}
	args  *relay.ConnectionArgs
	out   *{{ .Name }}Connection
}{
	{
		nodes: []*{{ .Name }}{},
		args:  &relay.ConnectionArgs{Before: nil, After: nil, First: &ZERO, Last: &ZERO},
		out: &{{ .Name }}Connection{
			Edges:    []*{{ .Name }}Edge{},
			PageInfo: relay.PageInfo{HasNextPage: false, HasPreviousPage: false, StartCursor: nil, EndCursor: nil},
		},
	},
	{
		nodes: nodes{{ .Name }},
		args:  &relay.ConnectionArgs{Before: nil, After: nil, First: &ZERO, Last: &ZERO},
		out: &{{ .Name }}Connection{
			Edges:    edges{{ .Name }},
			PageInfo: relay.PageInfo{HasNextPage: false, HasPreviousPage: false, StartCursor: &ONESTR, EndCursor: &FIVESTR},
		},
	},
	{
		nodes: nodes{{ .Name }},
		args:  &relay.ConnectionArgs{Before: nil, After: nil, First: &TWO, Last: &ZERO},
		out: &{{ .Name }}Connection{
			Edges:    edges{{ .Name }}[:2],
			PageInfo: relay.PageInfo{HasNextPage: true, HasPreviousPage: false, StartCursor: &ONESTR, EndCursor: &TWOSTR},
		},
	},
	{
		nodes: nodes{{ .Name }},
		args:  &relay.ConnectionArgs{Before: nil, After: nil, First: &ZERO, Last: &TWO},
		out: &{{ .Name }}Connection{
			Edges:    edges{{ .Name }}[3:],
			PageInfo: relay.PageInfo{HasNextPage: false, HasPreviousPage: true, StartCursor: &FOURSTR, EndCursor: &FIVESTR},
		},
	},
	{
		nodes: nodes{{ .Name }},
		args:  &relay.ConnectionArgs{Before: &FOURSTR, After: &TWOSTR, First: &ZERO, Last: &ZERO},
		out: &{{ .Name }}Connection{
			Edges:    edges{{ .Name }}[1:4],
			PageInfo: relay.PageInfo{HasNextPage: false, HasPreviousPage: false, StartCursor: &TWOSTR, EndCursor: &FOURSTR},
		},
	},
}

func Test{{ .Name }}ConnectionFromArray(t *testing.T) {
	empty := {{ .Name }}ConnectionFromArray(table{{ .Name }}ConnectionFromArray[0].nodes, nil)
	if empty != nil {
		t.Errorf("Expected nil output for nil args")
	}

	for i, e := range table{{ .Name }}ConnectionFromArray {
		out := {{ .Name }}ConnectionFromArray(e.nodes, e.args)
		if out == nil {
			t.Errorf("Unexpected nil output")
			return
		}

		// PageInfo
		if out.PageInfo.HasNextPage != e.out.PageInfo.HasNextPage {
			t.Errorf("%d: Has next page: got %v, want %v", i, out.PageInfo.HasNextPage, e.out.PageInfo.HasNextPage)
		}

		if out.PageInfo.HasPreviousPage != e.out.PageInfo.HasPreviousPage {
			t.Errorf("%d: Has previous page: got %v, want %v", i, out.PageInfo.HasPreviousPage, e.out.PageInfo.HasPreviousPage)
		}

		if out.PageInfo.StartCursor != nil || e.out.PageInfo.StartCursor != nil {
			if *out.PageInfo.StartCursor != *e.out.PageInfo.StartCursor {
				t.Errorf("%d: Start cursor: got %v, want %v", i, *out.PageInfo.StartCursor, *e.out.PageInfo.StartCursor)
			}
		}

		if out.PageInfo.EndCursor != nil || e.out.PageInfo.EndCursor != nil {
			if *out.PageInfo.EndCursor != *e.out.PageInfo.EndCursor {
				t.Errorf("%d: End cursor: got %v, want %v", i, *out.PageInfo.EndCursor, *e.out.PageInfo.EndCursor)
			}
		}

		// Edges
		if len(out.Edges) != len(e.out.Edges) {
			t.Errorf("%d: Edges length: got %d, want %d", i, len(out.Edges), len(e.out.Edges))
			return
		}

		for j, eedge := range e.out.Edges {
			oedge := out.Edges[j]
			if eedge.Cursor != oedge.Cursor {
				t.Errorf("%d: Edge #%d: Cursor: got %s, want %s", i, j, oedge.Cursor, eedge.Cursor)
			}
		}
	}
}

var table{{ .Name }}EdgesToReturn = []struct {
	edges  []*{{ .Name }}Edge
	before *string
	after  *string
	first  *int
	last   *int
	out    *{{ .Name }}Connection
}{
	{edges: []*{{ .Name }}Edge{}, before: nil, after: nil, first: &ZERO, last: &ZERO, out: table{{ .Name }}ConnectionFromArray[0].out},
	{edges: edges{{ .Name }}, before: nil, after: nil, first: &ZERO, last: &ZERO, out: table{{ .Name }}ConnectionFromArray[1].out},
	{edges: edges{{ .Name }}, before: nil, after: nil, first: &TWO, last: &ZERO, out: table{{ .Name }}ConnectionFromArray[2].out},
	{edges: edges{{ .Name }}, before: nil, after: nil, first: &ZERO, last: &TWO, out: table{{ .Name }}ConnectionFromArray[3].out},
	{edges: edges{{ .Name }}, before: &FOURSTR, after: &TWOSTR, first: &ZERO, last: &ZERO, out: table{{ .Name }}ConnectionFromArray[4].out},
}

func Test{{ .Name }}EdgesToReturn(t *testing.T) {
	for i, e := range table{{ .Name }}EdgesToReturn {
		out := {{ .Name|lcFirst }}EdgesToReturn(e.edges, e.before, e.after, e.first, e.last)
		// PageInfo
		if out.PageInfo.HasNextPage != e.out.PageInfo.HasNextPage {
			t.Errorf("%d: Has next page: got %v, want %v", i, out.PageInfo.HasNextPage, e.out.PageInfo.HasNextPage)
		}

		if out.PageInfo.HasPreviousPage != e.out.PageInfo.HasPreviousPage {
			t.Errorf("%d: Has previous page: got %v, want %v", i, out.PageInfo.HasPreviousPage, e.out.PageInfo.HasPreviousPage)
		}

		if out.PageInfo.StartCursor != nil || e.out.PageInfo.StartCursor != nil {
			if *out.PageInfo.StartCursor != *e.out.PageInfo.StartCursor {
				t.Errorf("%d: Start cursor: got %v, want %v", i, *out.PageInfo.StartCursor, *e.out.PageInfo.StartCursor)
			}
		}

		if out.PageInfo.EndCursor != nil || e.out.PageInfo.EndCursor != nil {
			if *out.PageInfo.EndCursor != *e.out.PageInfo.EndCursor {
				t.Errorf("%d: End cursor: got %v, want %v", i, *out.PageInfo.EndCursor, *e.out.PageInfo.EndCursor)
			}
		}

		// Edges
		if len(out.Edges) != len(e.out.Edges) {
			t.Errorf("%d: Edges length: got %d, want %d", i, len(out.Edges), len(e.out.Edges))
			return
		}

		for j, eedge := range e.out.Edges {
			oedge := out.Edges[j]
			if eedge.Cursor != oedge.Cursor {
				t.Errorf("%d: Edge #%d: Cursor: got %s, want %s", i, j, oedge.Cursor, eedge.Cursor)
			}
		}
	}
}

var table{{ .Name }}ApplyCursorsToEdges = []struct {
	edges  []*{{ .Name }}Edge
	before *string
	after  *string
	len    int
}{
	{edges: []*{{ .Name }}Edge{}, before: nil, after: nil, len: 0},
	{edges: edges{{ .Name }}, before: nil, after: nil, len: 5},
	{edges: edges{{ .Name }}, before: nil, after: &TWOSTR, len: 4},
	{edges: edges{{ .Name }}, before: &FOURSTR, after: nil, len: 4},
	{edges: edges{{ .Name }}, before: &FOURSTR, after: &TWOSTR, len: 3},
}

func Test{{ .Name }}ApplyCursorsToEdges(t *testing.T) {
	for i, e := range table{{ .Name }}ApplyCursorsToEdges {
		out := {{ .Name|lcFirst }}ApplyCursorsToEdges(e.edges, e.before, e.after)
		if len(out) != e.len {
			t.Errorf("%d: Length: got %d, want %d", i, len(out), e.len)
		}

		if len(out) > 0 {
			if cursor := out[len(out)-1].Cursor; e.before != nil && cursor != *e.before {
				t.Errorf("%d: Before: got %s, want %s", i, cursor, *e.before)
			}

			if cursor := out[0].Cursor; e.after != nil && cursor != *e.after {
				t.Errorf("%d: After: got %s, want %s", i, cursor, *e.after)
			}
		}
	}
}

var table{{ .Name }}HasPreviousPage = []struct {
	edges  []*{{ .Name }}Edge
	before *string
	after  *string
	last   *int
	out    bool
}{
	{edges: []*{{ .Name }}Edge{}, before: nil, after: nil, last: nil, out: false},
	{edges: edges{{ .Name }}, before: nil, after: nil, last: nil, out: false},
	{edges: edges{{ .Name }}, before: nil, after: nil, last: &ZERO, out: false},
	{edges: edges{{ .Name }}, before: nil, after: nil, last: &SIX, out: false},
	{edges: edges{{ .Name }}, before: nil, after: nil, last: &FOUR, out: true},
	{edges: edges{{ .Name }}, before: &FOURSTR, after: &TWOSTR, last: &FOUR, out: false},
	{edges: edges{{ .Name }}, before: &FOURSTR, after: &TWOSTR, last: &ONE, out: true},
}

func Test{{ .Name }}HasPreviousPage(t *testing.T) {
	for i, e := range table{{ .Name }}HasPreviousPage {
		out := {{ .Name|lcFirst }}HasPreviousPage(e.edges, e.before, e.after, e.last)
		if out != e.out {
			t.Errorf("%d: got %v, want %v", i, out, e.out)
		}
	}
}

var table{{ .Name }}HasNextPage = []struct {
	edges  []*{{ .Name }}Edge
	before *string
	after  *string
	first  *int
	out    bool
}{
	{edges: []*{{ .Name }}Edge{}, before: nil, after: nil, first: nil, out: false},
	{edges: edges{{ .Name }}, before: nil, after: nil, first: nil, out: false},
	{edges: edges{{ .Name }}, before: nil, after: nil, first: &ZERO, out: false},
	{edges: edges{{ .Name }}, before: nil, after: nil, first: &SIX, out: false},
	{edges: edges{{ .Name }}, before: nil, after: nil, first: &FOUR, out: true},
	{edges: edges{{ .Name }}, before: &FOURSTR, after: &TWOSTR, first: &FOUR, out: false},
	{edges: edges{{ .Name }}, before: &FOURSTR, after: &TWOSTR, first: &ONE, out: true},
}

func Test{{ .Name }}HasNextPage(t *testing.T) {
	for i, e := range table{{ .Name }}HasNextPage {
		out := {{ .Name|lcFirst }}HasNextPage(e.edges, e.before, e.after, e.first)
		if out != e.out {
			t.Errorf("%d: got %v, want %v", i, out, e.out)
		}
	}
}
`))
